version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_vsd_formar
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adrieladm
      POSTGRES_PASSWORD: adriel123
      POSTGRES_DB: vsd-formar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
